[build]
  command = ""
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."assets"]
  included_files = ["private_assets/**"]

# Every /assets/:name request goes to the function
[[redirects]]
  from = "/assets/:name"
  to = "/.netlify/functions/assets"
  status = 200