[build]
  command = ""
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."assets"]
  included_files = ["private_assets/**"]

[[redirects]]
  from = "/assets/*"
  to = "/.netlify/functions/assets/:splat"
  status = 200
  force = true