[build]
  # No build step; publish the repository root
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/assets/:name"
  to = "/.netlify/functions/assets"
  status = 200